services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-basic-mcp-app:dev
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    env_file:
      - .env